### ISSUE TITLE
openjdk-6 no longer available

### ISSUE THREAD

**Issue by rviertel** [zvakanaka/family-search-ubuntu#1]
Hi,

Thanks for creating this repository. I have used it previously  to install familysearch on Ubuntu 14.04, but I'm having trouble now on 16.04 because Openjdk 6 is no longer available. Any ideas on how to get around this?

Thanks,

**Comment by duckbrain** [comment]
This isn't the cleanest solution, but you can install the Windows version with wine.

**Comment by ghost** [comment]
I asked the question on askubuntu.com and somebody was able to provide instructions on how to install it directly

http://askubuntu.com/questions/832673/how-to-install-familysearch-indexing-on-ubuntu-16-04/832889#832889

**Comment by zvakanaka** [comment]
The installer has already been updated to work with 64-bit Linux, so this repo is no longer needed. Here's how to get JRE 6 though: [http://www.webupd8.org/2012/11/oracle-sun-java-6-installer-available.html](http://www.webupd8.org/2012/11/oracle-sun-java-6-installer-available.html)
